# Generated by Django 2.2.4 on 2019-08-13 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0002_auto_20190810_0149'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='is_private',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
