# Generated by Django 2.2.4 on 2019-08-13 04:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('folders', '0003_folder_is_private'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
