# Generated by Django 2.2.4 on 2019-08-19 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0002_auto_20190819_1307'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='parent_id',
            new_name='parent',
        ),
    ]
